version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./dist:/var/www/dist  # Для разработки (монтирование локальной папки)
      # Для production используйте:
      # - react-static:/var/www/dist
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3

# Раскомментируйте для production:
# volumes:
#   react-static:
