version: '3.9'

services:
  frontend:
    image: allower99/frontend:latest
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - frontend
      - backend  # Для доступа к backend

  backend:
    image: allower99/backend-app:latest
    container_name: backend
    hostname: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    restart: unless-stopped
    networks:
      - monitoring_net
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    network_mode: host  # Для мониторинга хоста, а не контейнера
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - monitoring_net
    depends_on:
      - prometheus

networks:
  monitoring_net:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres_data:
