version: '3.8'

services:
  react-app:
    image: ${DOCKER_IMAGE}:${TAG:-latest}
    ports:
      - "3000:80"  # На server1: 3000, server2: 3001
    volumes:
      - /etc/nginx:/etc/nginx:ro
      - /var/www/dist:/var/www/dist
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
