version: '3.8'

services:
  react-app:
    image: ${DOCKER_USERNAME}/react-app:latest
    ports:
      - "3000:80"  # Разные порты на разных серверах (3000/3001)
    volumes:
      - /etc/nginx:/etc/nginx:ro
      - /var/www/dist:/var/www/dist
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
